//
//  MyViewController.swift
//  BookShop
//
//  Created by Arthur on 05/01/16.
//  Copyright © 2016 Arthur. All rights reserved.
//

import UIKit

class MyViewController: UIViewController, UICollectionViewDataSource, UICollectionViewDelegate {

    @IBOutlet weak var menuButton: UIBarButtonItem!
    @IBOutlet weak var collectionView: UICollectionView!
    
    var books: [Book]?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.demotData()
        
        let image = UIImage(named: "onlyLogo")
        navigationItem.titleView = UIImageView(image: image)
        

        if self.revealViewController() != nil{
            menuButton.target = self.revealViewController()
            menuButton.action = "revealToggle:"
            self.view.addGestureRecognizer(self.revealViewController().panGestureRecognizer())
        }
    }
    
    func demotData(){
        let book1: Book = Book(dateiName: "Buch 1", autorName: "von Umberto Eco",titelName: "Nullnummer", preisName: 15.00, beschreibungName: "Mailand, 6. Juni 1992, nachts. Bei dem Journalisten Colonna ist eingebrochen worden. Die Diskette mit brisanten Informationen hat man nicht gefunden, Colonna sieht jetzt sein eigenes Leben bedroht. Auch er spielt ein Doppelspiel: Er soll eine Zeitung lancieren, die mit schmutzigen Gerüchten über die gute Gesellschaft arbeitet. Zugleich schreibt er als Ghostwriter ein Enthüllungsbuch über den programmierten Skandal.",
            merkmaleName: "Einband: gebundene Ausgabe\nSeitenzahl: 240\nErscheinungsdatum: 26.09.2015\nSprache: Deutsch\nISBN 978-3-446-24939-4\nVerlag: Hanser\nMaße(L/B/H): 208/128/25 mm", rezensionName: "Dieses Buch darf man sich nicht entgehen lassen. Wer den Semiotiker kennt wird sicher wieder positiv überrascht sein. Ein Muss !", anzahlName: 1)
        let book2: Book = Book(dateiName: "Buch 2", autorName: "von Ellen Berg",titelName: "Mach mir den Garten, Liebling!", preisName: 19.00, beschreibungName: "Die Lust am Gärtnern und am Gärtner… Zur Hölle mit dem Job! Statt der überfälligen Beförderung bekommt Luisa einen Fiesling vor die Nase gesetzt. Sie ist frustriert: 14-Stunden-Arbeitstage und Bürointrigen, wofür das alles? Ausgerechnet jetzt muss sie sich um den Schrebergarten ihrer Tante Ruth kümmern. Geht gar nicht, Komposthaufen statt Karriere ist definitiv keine Lösung.", merkmaleName: "Einband: gebundene Ausgabe\nSeitenzahl: 300\nErscheinungsdatum: 26.02.2015\nSprache: Deutsch\nISBN 222-3-450-24939-4\nVerlag: Hanser\nMaße(L/B/H): 220/140/25 mm", rezensionName: "Ein typischer Ellen Berg Roman, herrlich sarkastisch, locker, spannend und humorvoll. Der Roman ist flüssig, komplex, temporeich, kurzweilig und fesselnd geschrieben und hat mich von Anfang an gefangen genommen.", anzahlName: 1)
        let book3: Book = Book(dateiName: "Buch 3", autorName: "von Lucinda Riley",titelName: "Die Sturmschwestern", preisName: 12.49, beschreibungName: "Der Wind und das Wasser, das sind die großen Leidenschaften in Allys Leben, die sei zu ihrem Beruf gemacht hat: Sie ist Seglerin und hat bei manch riskanter Regatta auf den Meeren der Welt ihren Mut unter Beweis gestellt. Eines Tages aber stirbt völlig überraschend ihr geliebter Vater Pa Salt, und Ally reist zu dem Familiensitz am Genfer See.", merkmaleName: "Einband: gebundene Ausgabe\nSeitenzahl: 325\nErscheinungsdatum: 12.01.2014\nSprache: Deutsch\nISBN 222-3-490-24939-5\nVerlag: Helfer\nMaße(L/B/H): 220/140/25 mm", rezensionName: "Mich hat auch dieser Band um die sieben Schwestern absolut fasziniert und überzeugt. Mit hinreißenden Protagonisten und traumhaften Kulissen ist dieses Buch ein typisches Meisterwerk von Lucinda Riley. Ich bin schon sehr auf den nächsten Band der Reihe gespannt und kann es kaum erwarten weiter zu lesen.", anzahlName: 1)
        let book4: Book = Book(dateiName: "Buch 4", autorName: "von Michael Lüders",titelName: "Wer den Wind sät - Was westliche Politik im Orient anrichtet", preisName: 16.50, beschreibungName: "Wer den Wind sät, wird Sturm ernten - Michael Lüders beschreibt die westlichen Interventionen im Nahen und Mittleren Osten seit der Kolonialzeit und erklärt, was sie mit der aktuellen politischen Situation zu tun haben. Sein neues Buch liest sich wie ein Polit-Thriller - nur leider beschreibt es die Realität. Eine Geschichte erscheint in unterschiedlichem Licht, je nachdem, wo man beginnt sie zu erzählen.", merkmaleName: "Einband: gebundene Ausgabe\nSeitenzahl: 175\nErscheinungsdatum: 22.12.2015\nSprache: Deutsch\nISBN 244-3-490-24939-5\nVerlag: Helfer\nMaße(L/B/H): 220/140/25 mm", rezensionName: "Die Wahrheit steht nicht in der Bild-Zeitung und ideologisch sehr eng verwandten täglichen beinahe wie zentral gelenkten Veröffentlichungen! Danke für solche Informationen. Sie sind dünn gesäht, aber man kann sie finden.", anzahlName: 1)
        let book5: Book = Book(dateiName: "Buch 5", autorName: "von Sebastian Fitzek",titelName: "Passagier 23", preisName: 19.95, beschreibungName: "Jedes Jahr verschwinden auf hoher See rund 20 Menschen spurlos von Kreuzfahrtschiffen. Noch nie kam jemand zurück. Bis jetzt... Martin Schwartz, Polizeipsychologe, hat vor fünf Jahren Frau und Sohn verloren. Es geschah während eines Urlaubs auf dem Kreuzfahrtschiff „Sultan of the Seas“ – niemand konnte ihm sagen, was genau geschah.", merkmaleName: "Einband: gebundene Ausgabe\nSeitenzahl: 175\nErscheinungsdatum: 22.12.2015\nSprache: Deutsch\nISBN 244-3-490-24939-5\nVerlag: Helfer\nMaße(L/B/H): 220/140/25 mm", rezensionName: "Super Buch", anzahlName: 1)
        let book6: Book = Book(dateiName: "Buch 6", autorName: "von Nele Neuhaus",titelName: "Die Lebenden und die Toten", preisName:   24.95, beschreibungName: "Kriminalkommissarin Pia Kirchhoff will gerade in die Flitterwochen fahren, als sie ein Anruf erreicht: In der Nähe von Eschborn wurde eine ältere Dame aus dem Hinterhalt erschossen. Kurz darauf ereignet sich ein ähnlicher Mord: Eine Frau wird durch das Küchenfenster ihres Hauses tödlich getroffen. Beide Opfer hatten keine Feinde.", merkmaleName: "Einband: gebundene Ausgabe\nSeitenzahl: 400\nErscheinungsdatum: 25.09.2013\nSprache: Deutsch\nISBN 274-5-490-25679-5\nVerlag: Droemer Knauer Verlag\nMaße(L/B/H): 300/145/25 mm", rezensionName: "Typisch Nele Neuhaus Krimi. Spannend von der ersten bis zur letzten Seite. Ein Muss für alle Krimifans. Freue mich schon jetzt, auf ihre nächste Geschichte mit Pia- der Kommissarin.", anzahlName: 1)
        let book7: Book = Book(dateiName: "Buch 7", autorName: "von Jojo Moyes",titelName: "Ein ganz neues Leben", preisName:  7.50,
            beschreibungName: "«Du hast mich mitten ins Herz getroffen, Clark. Vom ersten Tag an, an dem du mit deinen lächerlichen Klamotten hereingestapft bist. Du hast mein Leben verändert.» Sechs Monate hatten Louisa Clark und Will Traynor zusammen. Ein ganzes halbes Jahr. Und diese sechs Monate haben beide verändert. Lou ist nicht mehr das Mädchen aus der Kleinstadt, das Angst vor seinen eigenen ",
            merkmaleName: "Einband: gebundene Ausgabe\nSeitenzahl: 150\nErscheinungsdatum: 21.10.2015\nSprache: Deutsch\nISBN 274-5-250-25679-5\nVerlag: Droemer Knauer Verlag\nMaße(L/B/H): 300/145/25 mm", rezensionName: "Super Buch", anzahlName: 1)
        let book8: Book = Book(dateiName: "Buch 8", autorName: "von Lea Schmidbauer, Kristina Magdalena Henn",titelName: "Ostwind - Aufbruch nach Ora", preisName:  9.50, beschreibungName: "Mika scheint endlich angekommen zu sein: seit einem Jahr wohnt sie nun auf Kaltenbach, kann Ostwind sehen, wann immer sie möchte und auch Milan, der jetzt auf dem Hof arbeitet, ist an ihrer Seite. Außerdem ist Mika eine kleine Berühmtheit. Pferdebesitzer aus ganz Deutschland legen weite Strecken zurück, um das Therapiezentrum Kaltenbach zu besuchen. Alles könnte perfekt sein. Doch dann gibt es ein schreckliches Gewitter ausgerechnet in", merkmaleName: "Einband: gebundene Ausgabe\nSeitenzahl: 200\nErscheinungsdatum: 21.12.2015\nSprache: Deutsch\nISBN 274-5-750-25679-5\nVerlag: C.H. Beck\nMaße(L/B/H): 300/145/25 mm", rezensionName: "Fazit: Dieses Buch hats in sich, zu Anfang ist es recht traurig im verlauf sehr spannend und zum Ende ebenfalls traurig. Ostwind 3 der letzte Teil? Nehmt Euch am besten eine Taschentücherbox dazu, denn die werdet Ihr brauchen. Irgendwie mag ich den Film schon gar nicht mehr sehen. *schnief*", anzahlName: 1)
        let book9: Book = Book(dateiName: "Buch 9", autorName: "von Jeff Kinney",titelName: "Gregs Tagebuch 10 - So ein Mist!", preisName:  25.00, beschreibungName: "Greg ist entsetzt, als seine Mom für die ganze Stadt ein elektronikfreies Wochenende organisieren will. Zwei Tage ohne Handy, Fernsehen und Computerspiele? Stattdessen gemeinsames Saubermachen im Park, Nachmittage in der freien Natur und ein altmodischer Limonadenstand? So ein Mist!, findet Greg und hat schon bei dem",
            merkmaleName: "Einband: gebundene Ausgabe\nSeitenzahl: 350\nErscheinungsdatum: 14.04.2011\nSprache: Deutsch\nISBN 274-5-490-24939-5\nVerlag: Helfer\nMaße(L/B/H): 300/145/25 mm", rezensionName: "Ich habe das Buch innerhalb von zwei Tagen gelesen so gefangen war ich. Es hat mir das Gefühl gegeben ein Kind dieser Familie zu sein.", anzahlName: 1)
        let book10: Book = Book(dateiName: "Buch 10", autorName: "von Georg Hoffmann",titelName: "Guinness World Records 2016", preisName:  16.45, beschreibungName: "Das Rekord-Buch, das alle Rekorde bricht!Willkommen zur neuesten Edition von Guinness World Records. Letztes Jahr haben wir 60. Jubiläum gebührend gefeiert - dieses Jahr knüpfen wir an diesen Erfolg an und präsentieren euch wieder ein brandneues Design, spannende, topaktuelle Rekorde und eine ganze Reihe origineller Fotos. Die Herausforderung ist es, jedes neue",
            merkmaleName: "Einband: gebundene Ausgabe\nSeitenzahl: 275\nErscheinungsdatum: 05.08.2013\nSprache: Deutsch\nISBN 274-5-750-25679-5\nVerlag: Ullstein Taschenbuchverlag\nMaße(L/B/H): 250/120/25 mm", rezensionName: "Das „Guinness World Records“, oder wie es eigentlich auf deutsch heißen müsste, Guinness Buch der Rekorde“ ist seit vielen Jahren ein konstanter Faktor bei Jahresbüchern. Egal, welchen Band man sich kauft, immer wieder kann man darüber staunen, wie verrückte, lustige und auch manchmal abstrakte Rekorde von Menschen, Tieren und natürlich der Natur aufgestellt werden.", anzahlName: 1)
        let book11: Book = Book(dateiName: "Buch 11", autorName: "von Jochen Schweizer",titelName: "Der perfekte Augenblick - Eine Anleitung für mehr Glück, Erfolg und Stärke", preisName:  19.99, beschreibungName: "Wie schaffe ich es, im richtigen Moment die richtigen Entscheidungen zu treffen? Wenn es einen Autor in Deutschland gibt, der Grenzerfahrungen positiv mit Leben erfüllt, ist es Jochen Schweizer. Der Unternehmer und prominente Investor des VOX-Formats Die Höhle der Löwen war Stuntman, brach Weltrekorde als Bungeejumper und macht mit seinem Unternehmen Umsätze in Millionenhöhe. Ob beim Fallschirmspringen, Fassadenklettern", merkmaleName: "Einband: gebundene Ausgabe\nSeitenzahl: 290\nErscheinungsdatum: 01.06.2010\nSprache: Deutsch\nISBN 274-5-750-25600-5\nVerlag: C.H. Beck\nMaße(L/B/H): 220/120/25 mm", rezensionName: "Liest sich sehr gut, empfehlenswert! Man kann ein bisschen lernen, aufzustehen, wird motiviert sein Leben selbst in Angriff zu nehmen. Schöne optische Aufmachung.", anzahlName: 1)
        let book12: Book = Book(dateiName: "Buch 12", autorName: "von Erin Hunter",titelName: "Warrior Cats Staffel 05/02 - Der Ursprung der Clans", preisName:  12.50, beschreibungName: "Die Katzen haben endlich eine neue Heimat gefunden. Doch das Zerwürfnis der Brüder Wolkenhimmel und Grauer Flug hat auch die Gruppe in zwei feindliche Lager gespalten. Ein junger Kater steht zwischen den Fronten und muss sich der schwierigsten Entscheidung seines Lebens stellen. Wolkenhimmel verwehrt jeder Katze, die krank oder schwach ist, den Zutritt zu seinem Wald. Er verstößt sogar ",
            merkmaleName: "Einband: gebundene Ausgabe\nSeitenzahl: 375\nErscheinungsdatum: 01.08.2010\nSprache: Deutsch\nISBN 274-5-750-27700-5\nVerlag: Ullstein Taschenbuchverlag\nMaße(L/B/H): 220/120/25 mm", rezensionName: "Super Buch! Kann ich jedem Katzenliebhaber empfehlen!", anzahlName: 1)
        let book13: Book = Book(dateiName: "Buch 13", autorName: "von Rebecca Gable",titelName: "Der Palast der Meere", preisName:  30.00, beschreibungName: "Mailand, 6. Juni 1992, nachts. Bei dem Journalisten Colonna ist eingebrochen worden. Die Diskette mit brisanten Informationen hat man nicht gefunden, Colonna sieht jetzt sein eigenes Leben bedroht. Auch er spielt ein Doppelspiel: Er soll eine Zeitung lancieren, die mit schmutzigen Gerüchten über die gute Gesellschaft arbeitet. Zugleich schreibt er als Ghostwriter ein Enthüllungsbuch über den programmierten Skandal.", merkmaleName: "Einband: gebundene Ausgabe\nSeitenzahl: 300\nErscheinungsdatum: 11.10.2011\nSprache: Deutsch\nISBN 274-5-750-27700-5\nVerlag: Ullstein Taschenbuchverlag\nMaße(L/B/H): 220/120/25 mm", rezensionName: "Super Buch! Nehmt Euch am besten eine Taschentücherbox dazu, denn die werdet Ihr brauchen. Irgendwie mag ich den Film schon gar nicht mehr sehen. *schnief*", anzahlName: 1)
        let book14: Book = Book(dateiName: "Buch 14", autorName: "von Micaela Jary",titelName: "Wie ein fernes Lied", preisName:  8.50, beschreibungName: "Hamburg,1939: Verzweifelt sieht Marga dem Zug hinterher, mit dem ihr Jugendfreund Michael in die Ferne reist. Seit sie denken kann, ist sie in den jüdischen Klarinettisten verliebt, zahllose Stunden verbrachte sie mit ihm in den Tanzlokalen der Hamburger Swingjugend. Obwohl seine Herkunft ihn zur Emigration nach Paris zwingt, ist Marga fest entschlossen, ihn wiederzusehen.", merkmaleName: "Einband: gebundene Ausgabe\nSeitenzahl: 180\nErscheinungsdatum: 02.08.2014\nSprache: Deutsch\nISBN 272-5-750-67709-5\nVerlag: Hanse\nMaße(L/B/H): 250/120/25 mm", rezensionName: "Ich bewundere Autoren und Autorinnen, die es tatsächlich schaffen jedes Jahr wieder ein Buch auf den Markt zu bringen. Natürlich besonders dann, wenn diese Bücher auch noch gut sind!", anzahlName: 1)
        let book15: Book = Book(dateiName: "Buch 15", autorName: "von Patricia Schröder",titelName: "Tilla, Zwieback und die verzwickte Zoorettung", preisName:  6.50, beschreibungName: "Tillas knallroter Eisenbahnwaggon rattert mit voller Fahrt ins nächste Abenteuer. Und wer daran zweifelt, dass Tilla neben der Riesenfledermaus Zwieback und vielen magischen Gegenständen auch noch einen ganzen Zoo im Waggon unterkriegt, der sollte einfach aufhören zu lesen. Andererseits: Wenn ein fieser Zoodirektor den Tieren das Leben zur Hölle macht und die arme kranke Giraffe sogar einschläfern will, dann muss man doch einfach dranbleiben, oder?", merkmaleName: "Einband: gebundene Ausgabe\nSeitenzahl: 200\nErscheinungsdatum: 15.05.2015\nSprache: Deutsch\nISBN 211-9-722-68009-5\nVerlag: Droemer Knauer Verlag\nMaße(L/B/H): 250/100/25 mm",
            rezensionName: "Werden es Tilla und Jannes schaffen den Zoo zu retten? Wird Tilla ihre geliebte Fledermaus wieder finden und trifft sie endlich ihre Eltern wieder? Um diese Fragen beantworten zu können, muss man einfach dieses wundervolle Buch lesen.", anzahlName: 1)
        let book16: Book = Book(dateiName: "Buch 16", autorName: "von Sabine Schoder",titelName: "Liebe ist was für Idioten. Wie mich.", preisName:  8.50, beschreibungName: "Optimistisch gesehen ist Vikis Leben eine Vollkatastrophe. Ihre Mutter: tot. Ihr Vater: ständig besoffen. Ihr Herz: gebrochen. Da kann auch die stärkste Überlebenskämpferin mal schwach werden, ein paar Tüten zu viel rauchen und mit einem Typen im Bett landen, den sie eigentlich total bescheuert findet: Jay Feretty. Aus tiefempfundener Abneigung wird plötzlich Liebe. Doch kaum traut Viki ihrem Glück, erfährt sie etwas über Jay, das ihr den Boden unte", merkmaleName: "Einband: gebundene Ausgabe\nSeitenzahl: 350\nErscheinungsdatum: 01.08.2015\nSprache: Deutsch\nISBN 290-9-750-67709-5\nVerlag: Hanse\nMaße(L/B/H): 280/120/25 mm",
            rezensionName: "Die spritzigen und wortgewandten Dialoge ziehen sich durch den gesamten Roman und lockern das hintergründig schwierige Thema so auf, dass ein leichter Jugendroman entsteht, der dennoch mit kritischen Themen umzugehen weiß.", anzahlName: 1)
        let book17: Book = Book(dateiName: "Buch 17", autorName: "von Ulrike Blatter",titelName: "Verliebt, verlobt, tot.", preisName:  12.50, beschreibungName: "Ehevorbereitungskurs? Das war gestern!Heutzutage helfen Krimis bei der Planung für das finale Ja-Wort.Hier werden alle denkbaren und undenkbaren Probleme rund um Herz und Schmerz geklärt: Was geschieht, wenn die Partner aus verschiedenen Kulturen oder sozialen Milieus stammen? Wenn die Karriere zugunsten der Ehe geopfert wird?", merkmaleName: "Einband: gebundene Ausgabe\nSeitenzahl: 140\nErscheinungsdatum: 15.10.2012\nSprache: Deutsch\nISBN 211-9-722-68009-5\nVerlag: Droemer Knauer Verlag\nMaße(L/B/H): 220/100/25 mm", rezensionName: "Ich bin absolut kein Fan von Kurzgeschichten, doch Ulrike hat mich überzeugt, dass solche zwischendurch auch gelesen werden können. Aufgrund meines Alters und Beziehungsstatus dachte ich, alles über die Liebe und das Rundherum zu wissen", anzahlName: 1)
        let book18: Book = Book(dateiName: "Buch 18", autorName: "von Kathrin Brückmann",titelName: "Der Eierkrieg", preisName:  14.50, beschreibungName: "Unter der Herrschaft des Grünen Grafen Kunibert erblüht das beschauliche Märheim. Ausheimische aus aller Herren Länder kommen, um die reiche Florauna zu bestaunen. Ob Faseltier oder Labergeiß, für jeden Besucher findet sich der richtige Fremdenführer. Doch der Erfolg des einen weckt Neid und Begehrlichkeiten des anderen: Isbert von der Zitterdelle, Herr über das benachbarte Schindburg, ersinnt einen Plan, um sich einen Teil vom Kuchen abzulurchen: Er ", merkmaleName: "Einband: gebundene Ausgabe\nSeitenzahl: 315\nErscheinungsdatum: 15.10.2012\nSprache: Deutsch\nISBN 290-9-715-67709-5\nVerlag: Hanse\nMaße(L/B/H): 280/120/25 mm",
            rezensionName: "Hab ich gelacht! Ein witziger Spaß für alle, die gern mit Worten spielen. Dabei bleibt die Spannung nicht auf der Strecke - Entführungen, fauler Zauber, Spionage, und was so mittelalterlich daherkommt, ist doch sehr aktuell. Wo kann man Faseltiere kaufen?", anzahlName: 1)
        let book19: Book = Book(dateiName: "Buch 19", autorName: "von Péter Gárdos",titelName: "Fieber am Morgen", preisName:  17.50, beschreibungName: "Wie viele haben geantwortet? Beinah zwanzig. Willst du jeder von ihnen zurückschreiben? Sie ist die Richtige, antwortete Miklós. Und woher weißt du das? Ich weiß es einfach. Im Juli 1945 wird Miklós, ein junger Ungar, nach Schweden gebracht. Er hat das KZ Bergen-Belsen überlebt, besteht nur noch aus Haut und Knochen, Zähne hat er auch keine mehr. Sein Arzt gibt ihm sechs Monate. Doch er hat andere ", merkmaleName: "Einband: gebundene Ausgabe\nSeitenzahl: 222\nErscheinungsdatum: 22.10.2002\nSprache: Deutsch\nISBN 290-9-722-67709-5\nVerlag: Donau\nMaße(L/B/H): 280/120/25 mm",
            rezensionName: "Wunderbar erzählt Gardos die Geschichte seiner Eltern und untermauert sie mit Auszügen aus den echten Briefen, die er von seiner Mutter bekommen hat. Mal anrührend oder gar traurig, mal mit viel Humor zeigt er dass Liebe Wunder bewirken kann.", anzahlName: 1)
        
        let book20: Book = Book(dateiName: "Buch 20", autorName: "von Patricia Schröder",titelName: "Schneegestöber", preisName:  22.40, beschreibungName: "Weihnachtsferien und ein großes Familientreffen auf einer kleinen Hallig. Alles könnte so schön sein auf der winzigen Insel mit den vielen Tieren: Leonie versteht sich prima mit ihrer Cousine Sünje, die Kinder toben jeden Tag mit Hund Kowalsky im Schnee herum und überhaupt ist es auf der Hallig mindestens so abenteuerlich wie bei Robinson Crusoe. Wenn sich nur Leonies miesepetrige Schwester nicht wie ein Stinkstiefel benehmen würde, ihre Oberzickencousine ", merkmaleName: "Einband: gebundene Ausgabe\nSeitenzahl: 210\nErscheinungsdatum: 22.01.2005\nSprache: Deutsch\nISBN 211-9-722-67709-5\nVerlag: Ullstein Taschenbuchverlag\nMaße(L/B/H): 280/120/25 mm",
            rezensionName: "Es wurden noch keine Bewertungen geschrieben.", anzahlName: 1)
        let book21: Book = Book(dateiName: "Buch 21", autorName: "von Roland Geisler",titelName: "Retributionem Auge um Auge-Zahn um Zahn", preisName:  12.40, beschreibungName: "Eine Tötungsserie erschüttert die Nürnberger Mordkommission. Die Opfer hängen gekreuzigt und mit einer besonderen Erkennungsmarke versehen auf der Oberleitung der Deutschen Bahn. Alle sind durch die Stromeinwirkung bis zur Unkenntlichkeit verbrannt. Das Ermittlerteam rund um Kriminalhauptkommissar Schorsch Bachmeyer steht vor einem Rätsel. ",
            merkmaleName: "Einband: gebundene Ausgabe\nSeitenzahl: 270\nErscheinungsdatum: 15.05.2009\nSprache: Deutsch\nISBN 211-9-722-68009-5\nVerlag: Helfer\nMaße(L/B/H): 250/100/25 mm",
            rezensionName: "Grandiose Geschichte - Spannung bis zur letzten Seite garantiert - Der Epilog ist das unerwartete Sahnehäubchen…mit dem ich als Leser keinesfalls gerechnet hätte! Bin gespannt auf die nächste Geschichte!", anzahlName: 1)
        let book22: Book = Book(dateiName: "Buch 22", autorName: "von Daniel H. Wilson",titelName: "Das Implantat", preisName:  9.95, beschreibungName: "Überlegenheit käuflich wäre? Mittels eines Implantats, das die geistigen und körperlichen Fähigkeiten immens steigert? Was, wenn sich diese Technologie nicht jeder leisten könnte? Daniel H. Wilson zeichnet ein erschreckend realistisches Zukunftsszenario - seit Gattaca hat niemand mehr die schöne neue Welt so treffend entlarvt.",
            merkmaleName: "Einband: gebundene Ausgabe\nSeitenzahl: 140\nErscheinungsdatum: 22.10.2012\nSprache: Deutsch\nISBN 211-9-722-62009-5\nVerlag: Droemer Knauer Verlag\nMaße(L/B/H): 220/100/25 mm",
            rezensionName: "Es wurden noch keine Bewertungen geschrieben.", anzahlName: 1)
        let book23: Book = Book(dateiName: "Buch 23", autorName: "von George R. R. Martin",titelName: "Das Lied von Eis und Feuer 10. Ein Tanz mit Drachen", preisName:  14.95, beschreibungName: "George Raymond Richard Martin wurde 1948 in New Jersey geboren. Sein Bestseller-Epos Das Lied von Eis und Feuer wurde als die vielfach ausgezeichnete Fernsehserie Game of Thrones verfilmt. George R.R. Martin wurde u. a. sechsmal der Hugo Award, zweimal der Nebula Award, dreimal der World Fantasy Award (u.a. für sein Lebenswerk und besondere Verdienste um die Fantasy) und dreimal der Locus Poll Award verliehen. 2013 errang er den ersten", merkmaleName: "Einband: gebundene Ausgabe\nSeitenzahl: 180\nErscheinungsdatum: 28.10.2011\nSprache: Deutsch\nISBN 211-9-722-62009-5\nVerlag: Droemer Knauer Verlag\nMaße(L/B/H): 220/100/25 mm",
            rezensionName: "Warum ich erst Band 10 rezensiere? Damit ich folgendes schreiben kann, ohne zu sehr zu spoilern: Ich glaube fest daran, Jon lebt!", anzahlName: 1)
        let book24: Book = Book(dateiName: "Buch 24", autorName: "von Viviana Mazza",titelName: "Die Geschichte von Malala", preisName:  19.95, beschreibungName: "Malala Yousafzai ist 11 Jahre alt und lebt mit ihrer Familie im Swat-Tal im Nordwesten Pakistans, als die Taliban ein Schulverbot für Mädchen verhängen. Doch Malala geht weiterhin zum Unterricht und fordert das Recht der Mädchen auf Bildung. Bis im Oktober 2012 ein Attentäter der Taliban ihren Schulbus stürmt und gezielt auf sie schießt. Wie ", merkmaleName: "Einband: gebundene Ausgabe\nSeitenzahl: 190\nErscheinungsdatum: 28.10.2012\nSprache: Deutsch\nISBN 239-9-722-62009-5\nVerlag: Droemer Knauer Verlag\nMaße(L/B/H): 220/100/25 mm",
            rezensionName: "Es wurden noch keine Bewertungen geschrieben.", anzahlName: 1)
        let book25: Book = Book(dateiName: "Buch 25", autorName: "von Cornelia Funke",titelName: "Gespensterjäger in der Gruselburg", preisName:  27.95, beschreibungName: "Auf Burg Dusterberg treibt ein Gespenst sein Unwesen, da ist sich Burgverwalter Theodor Wurm sicher. Allerdings weiß er nicht, dass es sich bei dem Ungeheuer um ein SPUMIDUV - einen Spuk mit dunkler Vergangenheit - handelt. Genauer gesagt um die Blutige Baronin, deren finstere Vergangenheit mit Burg Dusterberg verknüpft ist. Ihr muss dringend das Handwerk gelegt werden! Und wer wäre hierfür besser geeignet als die Gruselexperten Hedwig", merkmaleName: "Einband: gebundene Ausgabe\nSeitenzahl: 120\nErscheinungsdatum: 12.01.2012\nSprache: Deutsch\nISBN 239-9-712-62129-5\nVerlag: Hanser\nMaße(L/B/H): 220/100/25 mm",
            rezensionName: "Werden es Tilla und Jannes schaffen den den Inhaber der Burg zu retten? Eine witzige und unterhaltsame Geschichte für Groß und Klein!.", anzahlName: 1)
        let book26: Book = Book(dateiName: "Buch 26", autorName: "von Patricia Boll",titelName: "100 Rezepte - Brot backen", preisName:  4.95, beschreibungName: "Herzhaftes Bauernbrot, deftiges Landbrot, knuspriges Ciabatta oder dunkles Roggenbrot, Kornspitz, Milchbrötchen, Mohnhörnchen oder Sesambrezeln, schon bei dem Gedanken wird es jedem warm ums Herz. Wir haben für Sie 100 herrliche Rezepte gesammelt und aus probiert.", merkmaleName: "Einband: gebundene Ausgabe\nSeitenzahl: 180\nErscheinungsdatum: 12.09.2015\nSprache: Deutsch\nISBN 239-9-712-62150-5\nVerlag: Hanser\nMaße(L/B/H): 250/100/25 mm",
            rezensionName: "Für diesen Preis habe ich nicht so ein geniales Buch erwartet.Sehr schöne Bilder und super eingebunden.Die Rezepte sind einfach und gut erklärt.", anzahlName: 1)
        let book27: Book = Book(dateiName: "Buch 27", autorName: "von PONS & Co.",titelName: "PONS Schülerwörterbuch Englisch", preisName:  5.45, beschreibungName: "Schüler’s Liebling*: Das Wörterbuch für die komplette Schulzeit bis zum Abitur Gute Noten in Englisch - mit dem PONS Schülerwörterbuch hast du immer die richtige Übersetzung parat:Komplett: Das Wörterbuch enthält mit 130.000 Stichwörtern und Wendungen den Wortschatz aller aktuellen Schulbücher - perfekt abgestimmt auf die Lehrpläne und Themen im Unterricht.", merkmaleName: "Einband: gebundene Ausgabe\nSeitenzahl: 180\nErscheinungsdatum: 12.04.2015\nSprache: Deutsch\nISBN 239-9-712-62150-5\nVerlag: Droemer Knauer Verlag\nMaße(L/B/H): 250/100/25 mm",
            rezensionName: "Hat mir super bei meinen Vorbereitungen zum Abitur geholfen, ein MUSS für jeden Oberstufenschüler!", anzahlName: 1)
        let book28: Book = Book(dateiName: "Buch 28", autorName: "von Geneva Lee",titelName: "Royal Passion", preisName:  7.45, beschreibungName: "Auf ihrer Abschlussfeier an der Oxford University trifft Clara Bishop auf einen attraktiven Fremden. Ohne Vorwarnung zieht er sie an sich, küsst sie leidenschaftlich und verschwindet. Clara hat keine Ahnung, wer der Unbekannte ist – bis ein Bild von ihnen beiden in der Zeitung auftaucht: Ihr heißer Flirt ist Prinz Alexander von Cambridge, Thronfolger von England, königlicher Bad Boy", merkmaleName: "Einband: gebundene Ausgabe\nSeitenzahl: 195\nErscheinungsdatum: 12.02.2015\nSprache: Deutsch\nISBN 239-9-712-62150-5\nVerlag: Droemer Knauer Verlag\nMaße(L/B/H): 250/100/25 mm",
            rezensionName: "Ich empfehle dieses Buch jedem, der gerne etwas mit einem Prinzen lesen will, das ein bisschen in die Richtung von 'After Passion' oder 'Shades of Grey' lesen will. Das Buch ist sehr gut geschrieben!", anzahlName: 1)
        let book29: Book = Book(dateiName: "Buch 29", autorName: "von Nicholas Sparks",titelName: "Wenn du mich siehst", preisName:  13.45, beschreibungName: "Mitten auf einer einsamen nächtlichen Landstraße hat die 28-jährige Maria eine Reifenpanne. Ein Wagen hält, ein bedrohlich muskelbepackter Mann mit Schlägervisage steigt aus – und wechselt ihr freundlich den Reifen. Colin Hancock hat schon viele dumme Entscheidungen in seinem Leben getro en und bitter dafür büßen müssen, eine Beziehung ist das Letzte, was er sucht.", merkmaleName: "Einband: gebundene Ausgabe\nSeitenzahl: 215\nErscheinungsdatum: 12.12.2015\nSprache: Deutsch\nISBN 239-9-712-77750-5\nVerlag: Droemer Knauer Verlag\nMaße(L/B/H): 250/100/25 mm",
            rezensionName: "Mit seinen Romanen, die ausnahmslos die Bestsellerlisten eroberten und weltweit in über 50 Sprachen erscheinen, gilt Sparks als einer der meistgelesenen Autoren der Welt. Mehrere seiner Bestseller wurden erfolgreich verfilmt.", anzahlName: 1)
        let book30: Book = Book(dateiName: "Buch 30", autorName: "von Michael Robotham",titelName: "Der Schlafmacher", preisName:  18.45, beschreibungName: "Ein abgelegenes Bauernhaus in Somerset wird zum Schauplatz eines brutalen Mordes: Zwei Frauen, Mutter und Tochter, werden eines Nachts von einem skrupellosen Mörder hingerichtet. Doch trotz gründlicher Untersuchungen steht die Polizei vor einem Rätsel. Chief Superintendent Ronnie Cray bittet daher den erfahrenen Psychologen Joe O’Loughlin um Hilfe, der gleich mit mehreren verdächtigen Personen konfrontiert ist. Motive hätten sie alle", merkmaleName: "Einband: gebundene Ausgabe\nSeitenzahl: 290\nErscheinungsdatum: 01.01.2016\nSprache: Deutsch\nISBN 239-9-818-77750-5\nVerlag: Droemer Knauer Verlag\nMaße(L/B/H): 300/150/25 mm",
            rezensionName: "Wieder einmal, wie all seine Bücher, ein Meisterwerk. Michael Robotham versteht es, mit Wörtern zu jonglieren. Es ist ein wunderbarer neuer Teil seiner Serie. Kaum einer versteht es, so wunderschön zu schreiben. Es war purer Genuss, sein Buch zu lesen.", anzahlName: 1)
        
        self.books = [book1, book2, book3, book4, book5, book6, book7, book8, book9, book10, book11, book12, book13, book14, book15, book16, book17, book18, book19, book20, book21, book22, book23, book24, book25 ,book26 ,book27, book28, book29, book30]
    }
    
    func collectionView(collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        if books != nil{
            return 15
        }
        else {
            return 0
        }
    }
    
    
    func collectionView(collectionView: UICollectionView, cellForItemAtIndexPath indexPath: NSIndexPath) -> UICollectionViewCell{
            let cell: BookCell = collectionView.dequeueReusableCellWithReuseIdentifier("BookCell", forIndexPath: indexPath) as! BookCell
        let currentBook: Book = self.books![indexPath.row]
        cell.bookImageView.image = UIImage(named: currentBook.dateiName)
        cell.bookLabel.text = currentBook.titelName
        
        
        return cell
    }
    
    
    override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?) {
        super.prepareForSegue(segue, sender: sender)
       
        if segue.identifier == "toArtikelView" {
            let detailVC: ArtikelTableViewController? = segue.destinationViewController as? ArtikelTableViewController
            
            if detailVC != nil {
                let item: Book = self.books![self.collectionView.indexPathsForSelectedItems()![0].row]
                
                detailVC?.buecher = item
                detailVC?.buchTitelName = item.titelName
                detailVC?.buchImageName = item.dateiName
                detailVC?.buchAutorName = item.autorName
                detailVC?.buchPreisName = item.preisName
                detailVC?.buchBeschreibungName = item.beschreibungName
                detailVC?.buchMerkmaleName = item.merkmaleName
                detailVC?.buchRezensionName = item.rezensionName
                detailVC?.buchAnzahlName = item.anzahlName
            }
        }

    /*
    // MARK: - Navigation

    // In a storyboard-based application, you will often want to do a little preparation before navigation
    override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?) {
        // Get the new view controller using segue.destinationViewController.
        // Pass the selected object to the new view controller.
    }
    */

    }
}
